src/Entity/Board.php
<?php

namespace App\Entity;

use App\Repository\BoardRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BoardRepository::class)]
class Board
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $board_name = null;

    #[ORM\OneToMany(mappedBy: 'board', targetEntity: TaskList::class, cascade : ['remove'])]
    private Collection $taskLists;

    public function __construct()
    {
        $this->taskLists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBoardName(): ?string
    {
        return $this->board_name;
    }

    public function setBoardName(string $board_name): self
    {
        $this->board_name = $board_name;

        return $this;
    }

    /**
     * @return Collection<int, TaskList>
     */
    public function getTaskLists(): Collection
    {
        return $this->taskLists;
    }

    public function addTaskList(TaskList $taskList): self
    {
        if (!$this->taskLists->contains($taskList)) {
            $this->taskLists->add($taskList);
            $taskList->setBoard($this);
        }

        return $this;
    }

    public function removeTaskList(TaskList $taskList): self
    {
        if ($this->taskLists->removeElement($taskList)) {
            // set the owning side to null (unless already changed)
            if ($taskList->getBoard() === $this) {
                $taskList->setBoard(null);
            }
        }

        return $this;
    }

    public function __toString()
{
    return $this->board_name;
}

}

src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $task_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'task')]
    private ?TaskList $taskList = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTaskName(): ?string
    {
        return $this->task_name;
    }

    public function setTaskName(string $task_name): self
    {
        $this->task_name = $task_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTaskList(): ?TaskList
    {
        return $this->taskList;
    }

    public function setTaskList(?TaskList $taskList): self
    {
        $this->taskList = $taskList;

        return $this;
    }

    
}

src/Form/BoardType.php
<?php

namespace App\Form;

use App\Entity\Board;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BoardType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('board_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Board::class,
        ]);
    }
}

src/Controller/BoardController.php
<?php

namespace App\Controller;

use App\Entity\Board;
use App\Form\BoardType;
use App\Repository\BoardRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/board')]
class BoardController extends AbstractController
{
    #[Route('/', name: 'app_board_index', methods: ['GET'])]
    public function index(BoardRepository $boardRepository): Response
    {
        return $this->render('board/index.html.twig', [
            'boards' => $boardRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_board_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BoardRepository $boardRepository): Response
    {
        $board = new Board();
        $form = $this->createForm(BoardType::class, $board);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $boardRepository->save($board, true);

            return $this->redirectToRoute('app_board_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('board/new.html.twig', [
            'board' => $board,
            'form' => $form,
        ]);
    }


    #[Route('/{id}/edit', name: 'app_board_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Board $board, BoardRepository $boardRepository): Response
    {
        $form = $this->createForm(BoardType::class, $board);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $boardRepository->save($board, true);

            return $this->redirectToRoute('app_board_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('board/edit.html.twig', [
            'board' => $board,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_board_delete', methods: ['POST'])]
    public function delete(Request $request, Board $board, BoardRepository $boardRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$board->getId(), $request->request->get('_token'))) {
            $boardRepository->remove($board, true);
        }

        return $this->redirectToRoute('app_board_index', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/{id}', name: 'app_board_show', methods: ['GET'])]
    public function show(Board $board): Response
{
    $taskLists = $board->getTaskLists();
    // dd($taskLists->getValues());
    return $this->render('board/show.html.twig', [
        'board' => $board,
        'task_lists' => $taskLists,
    ]);
}
}

templates/board/_delete_form.html.twig
<form method="post" action="{{ path('app_board_delete', {'id': board.id}) }}" onsubmit="return confirm('Etes vous sur ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ board.id) }}">
    <button class="btn btn-danger">Supprimer le tableau</button>
</form>

templates/board/_form.html.twig
<div class="container">
{{ form_start(form) }}
    {{ form_widget(form) }}
    <br>
        <button class="btn btn-success">{{ button_label|default('Créer') }}</button>
{{ form_end(form) }}
</div>

templates/board/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier le tableau{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center">Modifier le tableau</h1>
<hr>
    {{ include('board/_form.html.twig', {'button_label': 'Validé la modification'}) }}
    {{ include('board/_delete_form.html.twig') }}

<hr>
    <a class="btn btn-info" href="{{ path('app_board_index') }}">Retour a la liste des tableaux</a>
</div>
{% endblock %}

templates/board/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Board index{% endblock %}

{% block body %}
<div class="container">

    <h1 class="text-center">Liste des tableaux</h1>
<table class="table">
    <thead>
        <tr>
            <th>#ID</th>
            <th>Nom</th>
            <th>nb de tasklist</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
    {% for board in boards %}
        <tr>
            <td>{{ board.id }}</td>
            <td>{{ board.boardName }}</td>
            <td>{{ board.taskLists.count() }}</td>
                        <td>

                <a class="btn btn-info" href="{{ path('app_board_show', {'id': board.id}) }}">Voir</a>
                <a class="btn btn-warning"href="{{ path('app_board_edit', {'id': board.id}) }}">Modifier</a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="3">Aucun tableau :(</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
    <a class="btn btn-success"href="{{ path('app_board_new') }}">Créer un nouveau</a>
             <a class="btn btn-outline-danger" href="{{ path('app_logout')}}">Logout</a> 

</div>


{% endblock %}

templates/board/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un nouveau tableau{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center">Créer un nouveau tableau</h1>
<hr>
    {{ include('board/_form.html.twig') }}
<hr>
    <a class="btn btn-danger"href="{{ path('app_board_index') }}">Retour à la liste des tableaux</a>
    </div>
{% endblock %}

templates/board/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Board{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center">[{{ board.id }}] - {{ board.boardName }}</h1>
         <hr> 
               <a class="btn btn-info" href="{{ path('app_task_list_new') }}">Ajouter une TaskList</a>

            <br>  
            <br>                                                                                                                                                                      </h1>
    <div class="row">
        {% for task_list in task_lists %}
            <div class="col-sm-4">  
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">{{ task_list.taskListName }}</h5> 
                        <div class="row">
                <div class="col-md-4">
        {{ include('task_list/_delete_form.html.twig') }}
                  </div>
                <div class="col-md-4">
        <a class="btn btn-sm btn-outline-warning" href="{{ path('app_task_list_edit', {'id': task_list.id}) }}">Modifier</a>  
</div>
</div>
 
        <hr>
        <ul>
            {% for task in task_list.task %}
                <li>{{ task.taskName }}                                    
                <p class="text-muted">- {{ task.description }}</p></li>
                <div class="row">
                <div class="col-md-4">
                {{ include('task/_delete_form.html.twig') }}<br>
                  </div>
                <div class="col-md-4">
<a class="btn btn-sm btn-outline-warning" href="{{ path('app_task_edit', {'id': task.id}) }}">Modifier</a> 
</div>
</div>
            {% endfor %}
        </ul>
        <hr>
        <a class="btn btn-success" href="{{ path('app_task_new') }}">Ajouter une Task</a>    
 
    </div>
</div>

        </div>
    {% endfor %}
</div>







<hr>
    <a class="btn btn-success" href="{{ path('app_board_index') }}">Retour a la liste des tableaux</a>

    <a class="btn btn-warning" href="{{ path('app_board_edit', {'id': board.id}) }}">Modifier le tableau</a>

    {{ include('board/_delete_form.html.twig') }}
    </div>

{% endblock %}